title: 第二本书
description: <!-- TODO: 书籍简短描述 -->
theme: jekyll-theme-cayman
lang: zh-CN
show_downloads: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
