title: SRv6网络基础教程
description: SRv6 基础原理、实验与生产实践
theme: jekyll-theme-cayman
lang: zh-CN
show_downloads: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
